#!/usr/bin/env bash

#while lop to print out bad luck , good luck and others
#bash loop that loop from 1-10
i=1 
while ((i<=10))
do
	if [ $i -eq 4 ] 
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi 
	((i+=1)) 
done
