#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:

hours=0
min=1
while [ $hours -le 12 ]
do
        echo "Hour: $hours"
        while [ $min -le 59 ]
        do
                echo  "$min"
                        ((min++))
        done
        min=1
        ((hours++))
done 
