#!/usr/bin/env bash
#nginx running as nginx user
#nginx must be listening on all active IPs on port 8080
sudo service nginx stop
sudo pkill apache2

sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx start

